### Objective of this Project
- scrape data from a public website
- organize the data as a dataframe
- export the data as an excel sheet

In [153]:
#Importong Libraries

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [154]:
#Website which is to be scraped for
url = "https://www.bbc.com/sport/football/premier-league/top-scorers"

In [155]:
try:
    response = requests.get(url)
    response.raise_for_status()
except Exception as e:
    print(e)
else:
    soup = BeautifulSoup(response.content,"html.parser")
    print("Succesful!")

Succesful!

In [156]:
players = soup.find("tbody").find_all("tr", class_ = "ssrcss-qqhdqi-TableRowBody e1icz100")
playerName = []
goalsScored = []
teamName = []
assists = []
matchesPlayed = []
total_shots = []

In [157]:
for player in players:
    names = player.find("div", class_ = "ssrcss-m6ah29-PlayerName e1n8xy5b1").get_text(strip = True)
    goals = int(player.find("div", class_ = "ssrcss-18ap757-CellWrapper ef9ipf0").get_text(strip=True))
    team_name = player.find("div", class_ = "ssrcss-qvpga1-TeamsSummary e1n8xy5b0").get_text(strip = True)
    stats = player.find_all("div", class_ = "ssrcss-1vo7v3r-CellWrapper ef9ipf0")
    assist = int(stats[0].get_text(strip=True))
    matches_Played = int(stats[3].get_text(strip=True))
    total_shot = int(stats[-3].get_text(strip=True))
    
    playerName.append(names)
    goalsScored.append(goals)
    teamName.append(team_name)
    assists.append(assist)
    matchesPlayed.append(matches_Played)
    total_shots.append(total_shot)

data = {
    'player' : playerName,
    'team' : teamName,
    'matches': matchesPlayed,
    'goals' : goalsScored,
    'assists' : assists,
    'shots' : total_shots
}

df_players = pd.DataFrame(data)

In [158]:
df_players

              player            team  matches  goals  assists  shots
0         E. Haaland        Man City       18     19        4     68
1        Igor Thiago       Brentford       18     11        1     37
2         A. Semenyo     Bournemouth       17      9        3     43
3         H. Ekitiké       Liverpool       17      8        2     35
4   D. Calvert-Lewin           Leeds       16      8        0     34
5        Richarlison           Spurs       18      7        3     29
6          M. Rogers     Aston Villa       18      7        3     33
7           P. Foden        Man City       16      7        2     39
8       N. Woltemade       Newcastle       15      7        1     26
9         D. Welbeck        Brighton       17      7        0     25
10         J. Mateta  Crystal Palace       18      7        0     48
11        João Pedro         Chelsea       18      6        3     29
12         B. Mbeumo         Man Utd       16      6        1     42
13         K. Schade       Brentford       17      6        1     29
14   Bruno Fernandes         Man Utd       17      5        7     46
15         H. Wilson          Fulham       17      5        4     32
16        Pedro Neto         Chelsea       18      5        3     29
17   Bruno Guimarães       Newcastle       17      5        2     24
18        O. Watkins     Aston Villa       18      5        1     33
19          J. Bowen        West Ham       18      5        1     45
20         J. Kroupi     Bournemouth       14      5        0     16
21       Z. Flemming         Burnley       15      5        0     18
22       V. Gyökeres         Arsenal       16      5        0     27
23       L. Trossard         Arsenal       14      4        3     23
24          C. Gakpo       Liverpool       16      4        3     37
25     Mohamed Salah       Liverpool       14      4        3     35
26        E. Buendía     Aston Villa       16      4        2     20
27            E. Eze         Arsenal       15      4        2     31
28        R. Jiménez          Fulham       17      4        2     33
29      T. Reijnders        Man City       17      4        2     32
30           B. Saka         Arsenal       16      4        2     41
31  K. Dewsbury-Hall         Everton       15      4        2     17
32         I. Ndiaye         Everton       16      4        2     20
33    R. Gravenberch       Liverpool       16      4        2     18
34      M. Tavernier     Bournemouth       18      4        2     35
35          D. Malen     Aston Villa       18      4        1     24
36         C. Wilson        West Ham       15      4        1     19
37          Casemiro         Man Utd       16      4        1     25
38        J. Anthony         Burnley       18      4        1     17
39      E. Fernández         Chelsea       17      4        1     34
40         L. Nmecha           Leeds       15      4        0     14
41         W. Isidor      Sunderland       18      4        0     31

In [159]:
df_players.describe()

         matches      goals    assists      shots
count  42.000000  42.000000  42.000000  42.000000
mean   16.571429   5.619048   1.761905  30.785714
std     1.271505   2.686483   1.410925  10.568097
min    14.000000   4.000000   0.000000  14.000000
25%    16.000000   4.000000   1.000000  24.000000
50%    17.000000   5.000000   2.000000  31.000000
75%    18.000000   6.750000   2.750000  35.000000
max    18.000000  19.000000   7.000000  68.000000

In [161]:
df_players.to_excel('Premier League Top Scorers.xlsx', index = False)